#!/bin/bash

echo "🔧 VARIABLES DE ENTORNO PARA RENDER"
echo "=================================="
echo ""
echo "Ve al dashboard de Render > tu servicio > Environment"
echo "Y agrega estas variables de entorno:"
echo ""
echo "TRUST_PROXY=true"
echo "COOKIE_SECURE=true"
echo "COOKIE_SAMESITE=none"
echo "NODE_ENV=production"
echo ""
echo "# Frontend URLs"
echo "FRONTEND_URL=https://bdo-client.vercel.app"
echo "EMAIL_VERIFICATION_URL=https://bdo-client.vercel.app/auth/verify-email?token={{token}}"
echo "PASSWORD_RESET_URL=https://bdo-client.vercel.app/auth/reset-password?token={{token}}"
echo ""
echo "# Cloudflare R2 Storage"
echo "STORAGE_DRIVER=cloudflare"
echo "CLOUDFLARE_ACCOUNT_ID=f5a8cb8424c5d6a19d528a252365d348"
echo "CLOUDFLARE_R2_BUCKET=bitacora-files"
echo "CLOUDFLARE_R2_ACCESS_KEY_ID=d96e6b751a5081660efb14ce12b06a35"
echo "CLOUDFLARE_R2_SECRET_ACCESS_KEY=9e22c8ccf1559982db9dc233e77a0e3bc5e35a07b2ce3540ff002177fbeb5c24"
echo ""
echo "# Server URLs"
echo "SERVER_PUBLIC_URL=https://bdo-server2.onrender.com"
echo "BASE_URL=https://bdo-server2.onrender.com"
echo ""
echo "🚨 IMPORTANTE: Después de agregar estas variables, redeploya el servicio"
